<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ShopsKichijojiHarajukuShibuyaYoyogiueharaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('shops')->insert([
            ['name' => 'alt', 'gender_id' => 1, 'prefecture_id' => 13, 'area_id' => 9, 'city' => '杉並区', 'address' => '松庵3-13-32', 'building' => '', 'instagram_url' => 'https://www.instagram.com/alt_store_official', 'holiday' => '月曜日、不定休', 'business_hour' => '13:00-19:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'Orfeo', 'gender_id' => 1, 'prefecture_id' => 13, 'area_id' => 9, 'city' => '武蔵野市', 'address' => '吉祥寺南町1-8-11', 'building' => '弥生ビル２F', 'instagram_url' => 'https://www.instagram.com/orfeokichijoji', 'holiday' => '', 'business_hour' => '12:00-20:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'N . vintage', 'gender_id' => 1, 'prefecture_id' => 13, 'area_id' => 9, 'city' => '武蔵野市', 'address' => '吉祥寺本町4丁目6-2', 'building' => '', 'instagram_url' => 'https://www.instagram.com/_n_vintage_', 'holiday' => '木曜日', 'business_hour' => '平日13:00-19:00 土日祝12:00-19:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'AMBER LION', 'gender_id' => 1, 'prefecture_id' => 13, 'area_id' => 9, 'city' => '武蔵野市', 'address' => '祥寺南町1-16-11', 'building' => '萩上ビル202', 'instagram_url' => 'https://www.instagram.com/kichijoji_amberlion', 'holiday' => '', 'business_hour' => '12:00-20:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'Zootie', 'gender_id' => 1, 'prefecture_id' => 13, 'area_id' => 9, 'city' => '武蔵野市', 'address' => '吉祥寺本町2-26-12', 'building' => '', 'instagram_url' => 'https://www.instagram.com/zootievintage', 'holiday' => '', 'business_hour' => '12:00~20:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'LittleBrothers', 'gender_id' => 1, 'prefecture_id' => 13, 'area_id' => 9, 'city' => '武蔵野市', 'address' => '吉祥寺南町1-16-11', 'building' => '', 'instagram_url' => 'https://www.instagram.com/littlebrothers_kichijoji', 'holiday' => '', 'business_hour' => '平日13:00~20:00 土日祝11:00~20:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'フラミンゴ', 'gender_id' => 1, 'prefecture_id' => 13, 'area_id' => 9, 'city' => '武蔵野市', 'address' => '吉祥寺南町1-17-9', 'building' => 'メゾンブランカB棟2F', 'instagram_url' => 'https://www.instagram.com/flamingo_kichijoji', 'holiday' => '', 'business_hour' => '平日12:00-21:00 土日祝 11:00-21:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'NEW YORK JOE EXCHANGE', 'gender_id' => 1, 'prefecture_id' => 13, 'area_id' => 9, 'city' => '武蔵野市', 'address' => '吉祥寺南町1-15-14', 'building' => '', 'instagram_url' => 'https://www.instagram.com/newyorkjoe_kichijoji', 'holiday' => '', 'business_hour' => '12:00-20:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'ROLE.', 'gender_id' => 1, 'prefecture_id' => 13, 'area_id' => 9, 'city' => '武蔵野市', 'address' => '吉祥寺南町1-15-16', 'building' => '', 'instagram_url' => 'https://www.instagram.com/role_vintage', 'holiday' => '', 'business_hour' => '12:00-19:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'dracaeana NORTH', 'gender_id' => 1, 'prefecture_id' => 13, 'area_id' => 9, 'city' => '武蔵野市', 'address' => '吉祥寺本町1-8-1', 'building' => '', 'instagram_url' => 'https://www.instagram.com/dracaena_north', 'holiday' => '', 'business_hour' => '11:00-20:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'YOUNGBLOODS', 'gender_id' => 3, 'prefecture_id' => 13, 'area_id' => 9, 'city' => '武蔵野市', 'address' => '御殿山1-2-2', 'building' => '', 'instagram_url' => 'https://www.instagram.com/youngbloods_clothing', 'holiday' => '', 'business_hour' => '13:00-21:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'YEAH', 'gender_id' => 3, 'prefecture_id' => 13, 'area_id' => 9, 'city' => '武蔵野市', 'address' => '吉祥寺本町2-14-26', 'building' => '', 'instagram_url' => 'https://www.instagram.com/yeahkichijoji', 'holiday' => '', 'business_hour' => '12:00-20:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'Ensemble', 'gender_id' => 1, 'prefecture_id' => 13, 'area_id' => 9, 'city' => '武蔵野市', 'address' => '吉祥寺南町1-10-6', 'building' => '', 'instagram_url' => 'https://www.instagram.com/ensemble_kichijoji', 'holiday' => '水曜日', 'business_hour' => '平日14:00-21:00 土日祝12:00-20:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => '原宿シカゴ 吉祥寺店', 'gender_id' => 1, 'prefecture_id' => 13, 'area_id' => 9, 'city' => '武蔵野市', 'address' => '吉祥寺本町2-13-6', 'building' => '', 'instagram_url' => 'https://www.instagram.com/harajukuchicago_official', 'holiday' => '', 'business_hour' => '12:00-19:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'ANIS', 'gender_id' => 2, 'prefecture_id' => 13, 'area_id' => 9, 'city' => '武蔵野市', 'address' => '吉祥寺本町2-2-7', 'building' => 'プラザオギノ301', 'instagram_url' => 'https://www.instagram.com/anis60svintage', 'holiday' => '不定休', 'business_hour' => '13:00-19:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'nico', 'gender_id' => 1, 'prefecture_id' => 13, 'area_id' => 9, 'city' => '武蔵野市', 'address' => '吉祥寺南町1-1-2', 'building' => '大竹ビル ２階', 'instagram_url' => 'https://www.instagram.com/nico.bank', 'holiday' => '', 'business_hour' => '14:00-21:00 holiday 13:00-21:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'TokyoDressLab.', 'gender_id' => 2, 'prefecture_id' => 13, 'area_id' => 9, 'city' => '武蔵野市', 'address' => '吉祥寺本町2-22-5', 'building' => '201', 'instagram_url' => 'https://www.instagram.com/tokyodresslab', 'holiday' => '木曜日', 'business_hour' => '12:00-20:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'Santa Monica', 'gender_id' => 1, 'prefecture_id' => 13, 'area_id' => 9, 'city' => '武蔵野市', 'address' => '吉祥寺南町1-16-11', 'building' => '', 'instagram_url' => 'https://www.instagram.com/santamonica_kichijouji', 'holiday' => '', 'business_hour' => '11:00-20:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'VORO', 'gender_id' => 1, 'prefecture_id' => 13, 'area_id' => 9, 'city' => '武蔵野市', 'address' => '吉祥寺本町2-17-11', 'building' => '', 'instagram_url' => 'https://www.instagram.com/volosupply', 'holiday' => '', 'business_hour' => '', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'kokoro', 'gender_id' => 3, 'prefecture_id' => 13, 'area_id' => 9, 'city' => '武蔵野市', 'address' => '吉祥寺本町2-26-9', 'building' => '', 'instagram_url' => 'https://www.instagram.com/kichijojinokokoro', 'holiday' => '', 'business_hour' => '12:00-19:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'SAFARI 吉祥寺店', 'gender_id' => 1, 'prefecture_id' => 13, 'area_id' => 9, 'city' => '武蔵野市', 'address' => '吉祥寺南町1-16-11', 'building' => '', 'instagram_url' => 'https://www.instagram.com/safari.kichijoji', 'holiday' => '', 'business_hour' => '12:00-20:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'garnish Vintage', 'gender_id' => 1, 'prefecture_id' => 13, 'area_id' => 9, 'city' => '武蔵野市', 'address' => '吉祥寺本町4-1-2', 'building' => '', 'instagram_url' => 'https://www.instagram.com/garnish_vintage', 'holiday' => '', 'business_hour' => '13:00-19:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'Boogie', 'gender_id' => 1, 'prefecture_id' => 13, 'area_id' => 9, 'city' => '武蔵野市', 'address' => '吉祥寺本町1-20-15', 'building' => '東永ビル2F', 'instagram_url' => 'https://www.instagram.com/boogie_used_clothing', 'holiday' => '', 'business_hour' => '平日14:00-21:00 土日祝13:00-21:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'dracaena', 'gender_id' => 1, 'prefecture_id' => 13, 'area_id' => 9, 'city' => '武蔵野市', 'address' => '吉祥寺南町1-16-1', 'building' => '', 'instagram_url' => 'https://www.instagram.com/dracaena_kichijoji', 'holiday' => '', 'business_hour' => '11:00-20:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'cherry loville', 'gender_id' => 1, 'prefecture_id' => 13, 'area_id' => 9, 'city' => '武蔵野市', 'address' => '吉祥寺南町1-15-1', 'building' => '2F', 'instagram_url' => 'https://www.instagram.com/cherryloville', 'holiday' => '', 'business_hour' => '13:00-20:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'ADULT', 'gender_id' => 3, 'prefecture_id' => 13, 'area_id' => 9, 'city' => '武蔵野市', 'address' => '吉祥寺本町1-38-5', 'building' => '', 'instagram_url' => 'https://www.instagram.com/adultusedandselect', 'holiday' => '', 'business_hour' => '14:00-20:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'Lemontea', 'gender_id' => 1, 'prefecture_id' => 13, 'area_id' => 3, 'city' => '渋谷区', 'address' => '神宮前6-11-18', 'building' => '', 'instagram_url' => 'https://www.instagram.com/lemontea_tokyo', 'holiday' => '', 'business_hour' => '12:00-20:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'Mr. Clean', 'gender_id' => 1, 'prefecture_id' => 13, 'area_id' => 19, 'city' => '渋谷区', 'address' => '富ヶ谷1-35-4', 'building' => 'セトルMS代々木公園 1F', 'instagram_url' => 'https://www.instagram.com/mrcleantomigaya', 'holiday' => '月曜日', 'business_hour' => '12:00-19:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'GRACE', 'gender_id' => 1, 'prefecture_id' => 13, 'area_id' => 2, 'city' => '渋谷区', 'address' => '神南1-14-1', 'building' => '', 'instagram_url' => 'https://www.instagram.com/mr.grace_vintage', 'holiday' => '', 'business_hour' => '12:30-20:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'BRACKETS', 'gender_id' => 1, 'prefecture_id' => 13, 'area_id' => 2, 'city' => '渋谷区', 'address' => '神山町13-13', 'building' => '', 'instagram_url' => 'https://www.instagram.com/brackets_shibuya', 'holiday' => '', 'business_hour' => '12:00-22:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'illminate', 'gender_id' => 3, 'prefecture_id' => 13, 'area_id' => 2, 'city' => '渋谷区', 'address' => '神南1-7-8', 'building' => '3F', 'instagram_url' => 'https://www.instagram.com/illminate', 'holiday' => '', 'business_hour' => '12:00-20:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'davids clothing', 'gender_id' => 3, 'prefecture_id' => 13, 'area_id' => 2, 'city' => '渋谷区', 'address' => '渋谷1-22-4', 'building' => '', 'instagram_url' => 'https://www.instagram.com/davidstokyojapan', 'holiday' => '', 'business_hour' => '12:00-20:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'TOXGO', 'gender_id' => 1, 'prefecture_id' => 13, 'area_id' => 3, 'city' => '渋谷区', 'address' => '神宮前3-27-13', 'building' => 'B1', 'instagram_url' => 'https://www.instagram.com/toxgo', 'holiday' => '', 'business_hour' => '12:00-20:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'PENGUIN TRIPPER', 'gender_id' => 1, 'prefecture_id' => 13, 'area_id' => 3, 'city' => '渋谷区', 'address' => '神宮前4-25-3', 'building' => '', 'instagram_url' => 'https://www.instagram.com/penguin_tripper', 'holiday' => '', 'business_hour' => '13:00-18:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'Props Store Annex', 'gender_id' => 3, 'prefecture_id' => 13, 'area_id' => 3, 'city' => '渋谷区', 'address' => '神宮前2-30-5', 'building' => 'トーカン原宿キャステール 0002', 'instagram_url' => 'https://www.instagram.com/propsstore_annex', 'holiday' => '', 'business_hour' => '13:00-19:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'fovos', 'gender_id' => 1, 'prefecture_id' => 13, 'area_id' => 3, 'city' => '渋谷区', 'address' => '神宮前5-13-14', 'building' => 'Sekine House B1F', 'instagram_url' => 'https://www.instagram.com/fovos_tokyo', 'holiday' => '', 'business_hour' => '12:00-20:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'STUDIO KONBINI', 'gender_id' => 1, 'prefecture_id' => 13, 'area_id' => 3, 'city' => '渋谷区', 'address' => '神宮前3-15-8', 'building' => 'シャンブル15 309', 'instagram_url' => 'https://www.instagram.com/studiokonbini', 'holiday' => '水曜日', 'business_hour' => '14:00-21:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'PITTZZ', 'gender_id' => 1, 'prefecture_id' => 13, 'area_id' => 3, 'city' => '渋谷区', 'address' => '神宮前2-16-16', 'building' => 'KUROSU3ビル2F', 'instagram_url' => 'https://www.instagram.com/pittzz_tokyo', 'holiday' => '', 'business_hour' => 'Monday-Saturday 13:00-21:00 Sunday 13:00-20:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'milli vintage', 'gender_id' => 2, 'prefecture_id' => 13, 'area_id' => 19, 'city' => '渋谷区', 'address' => '富ケ谷1-9-14', 'building' => '', 'instagram_url' => 'https://www.instagram.com/milli_vintage', 'holiday' => '水曜日、日曜日', 'business_hour' => '14:00-19:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'Color at Against', 'gender_id' => 1, 'prefecture_id' => 13, 'area_id' => 19, 'city' => '渋谷区', 'address' => '西原3-14-6', 'building' => '', 'instagram_url' => 'https://www.instagram.com/color_at_against', 'holiday' => '水曜日', 'business_hour' => '平日14:00-19:00 日祝13:00-18:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'dojoe', 'gender_id' => 1, 'prefecture_id' => 13, 'area_id' => 19, 'city' => '渋谷区', 'address' => '元代々木町9-8', 'building' => '', 'instagram_url' => 'https://www.instagram.com/dojoe_tokyo', 'holiday' => '', 'business_hour' => '平日14:00-20:00 土日祝13:00-20:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'CaNARi', 'gender_id' => 1, 'prefecture_id' => 13, 'area_id' => 19, 'city' => '渋谷区', 'address' => '上原1-33-16', 'building' => '', 'instagram_url' => 'https://www.instagram.com/canari_yoyogiuehara', 'holiday' => '', 'business_hour' => '月〜土 13:00-21:00 日・祝 12:00-20:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'OKIDOKI', 'gender_id' => 3, 'prefecture_id' => 13, 'area_id' => 19, 'city' => '渋谷区', 'address' => '富ヶ谷1-9-15', 'building' => '', 'instagram_url' => 'https://www.instagram.com/okidoki_mens', 'holiday' => '', 'business_hour' => '12:00-20:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'Chief vintage', 'gender_id' => 2, 'prefecture_id' => 13, 'area_id' => 19, 'city' => '渋谷区', 'address' => '上原1-23-9', 'building' => '', 'instagram_url' => 'https://www.instagram.com/chief_vintage_', 'holiday' => '不定休', 'business_hour' => '14:00-19:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'SNAK', 'gender_id' => 1, 'prefecture_id' => 13, 'area_id' => 19, 'city' => '渋谷区', 'address' => '上原3-8-2', 'building' => '', 'instagram_url' => 'https://www.instagram.com/snak_tokyo', 'holiday' => '水曜日', 'business_hour' => '平日14:00-21:00 土日祝13:00-20:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => '放課後の思い出', 'gender_id' => 1, 'prefecture_id' => 13, 'area_id' => 19, 'city' => '渋谷区', 'address' => '上原1-47-4', 'building' => '金子ビル1F', 'instagram_url' => 'https://www.instagram.com/houkago_no_omoide', 'holiday' => '', 'business_hour' => '', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'アヤワスカ洋服店', 'gender_id' => 1, 'prefecture_id' => 13, 'area_id' => 19, 'city' => '渋谷区', 'address' => '富ヶ谷1-51-2', 'building' => 'デュオパークビルMサイドB1', 'instagram_url' => 'https://www.instagram.com/ayahuasca_clothes', 'holiday' => '水曜日', 'business_hour' => '平日15:00-22:00 土日祝日13:00-20:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'are you hungry？', 'gender_id' => 1, 'prefecture_id' => 13, 'area_id' => 19, 'city' => '渋谷区', 'address' => '元代々木町9-2-101', 'building' => '', 'instagram_url' => 'https://www.instagram.com/hungry_areyou', 'holiday' => '', 'business_hour' => '', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
        ]);
    }
}
