<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ShopsMiyagiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('shops')->insert([
            ['name' => 'Across the Universe', 'gender_id' => 1, 'prefecture_id' => 4, 'area_id' => 27, 'city' => '仙台市', 'address' => '青葉区五橋2-4-15', 'building' => '', 'instagram_url' => 'https://www.instagram.com/acrosstheuniverse1977', 'holiday' => '月曜日', 'business_hour' => '12:00-18:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'biscco', 'gender_id' => 1, 'prefecture_id' => 4, 'area_id' => 27, 'city' => '仙台市', 'address' => '青葉区本町2-5-16', 'building' => '', 'instagram_url' => 'https://www.instagram.com/biscco288', 'holiday' => '水曜＆第二火曜日定休', 'business_hour' => '12:00-19:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'chuple', 'gender_id' => 2, 'prefecture_id' => 4, 'area_id' => 27, 'city' => '仙台市', 'address' => '青葉区一番町1-4-26', 'building' => '', 'instagram_url' => 'https://www.instagram.com/chuple_sendai', 'holiday' => '', 'business_hour' => '12:00-19:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'CLIMB', 'gender_id' => 1, 'prefecture_id' => 4, 'area_id' => 27, 'city' => '仙台市', 'address' => '青葉区中央2-6-14', 'building' => '', 'instagram_url' => 'https://www.instagram.com/climb.sendai', 'holiday' => '', 'business_hour' => 'WEEKDAY 14:00-19:00 HOLIDAY 12:00-19:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'GREENROOM', 'gender_id' => 1, 'prefecture_id' => 4, 'area_id' => 27, 'city' => '仙台市', 'address' => '青葉区一番町2-5-6', 'building' => '3F', 'instagram_url' => 'https://www.instagram.com/greenroom256', 'holiday' => '', 'business_hour' => '', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'Hi-smile', 'gender_id' => 1, 'prefecture_id' => 4, 'area_id' => 27, 'city' => '仙台市', 'address' => '青葉区中央2-1-15', 'building' => '仙台マンション307', 'instagram_url' => 'https://www.instagram.com/hi_smile_sendai', 'holiday' => '', 'business_hour' => '11:00-20:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'MELLOW CLASSIC 八幡店', 'gender_id' => 1, 'prefecture_id' => 4, 'area_id' => 27, 'city' => '仙台市', 'address' => '青葉区八幡3-1-1', 'building' => '', 'instagram_url' => 'https://www.instagram.com/mellow.classic', 'holiday' => '月曜', 'business_hour' => '12:00-18:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'MELLOW CLASSIC 木町店', 'gender_id' => 1, 'prefecture_id' => 4, 'area_id' => 27, 'city' => '仙台市', 'address' => '青葉区木町5-29', 'building' => '', 'instagram_url' => 'https://www.instagram.com/mellow.classic', 'holiday' => '水曜', 'business_hour' => '12:00-18:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'nariwai', 'gender_id' => 1, 'prefecture_id' => 4, 'area_id' => 27, 'city' => '仙台市', 'address' => '青葉区本町2-6-23', 'building' => '', 'instagram_url' => 'https://www.instagram.com/nariwai_japan', 'holiday' => '', 'business_hour' => '', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'ooooo', 'gender_id' => 1, 'prefecture_id' => 4, 'area_id' => 27, 'city' => '仙台市', 'address' => '青葉区本町2-14-20', 'building' => '大貴本町ビル4F', 'instagram_url' => 'https://www.instagram.com/ooooo_sendai', 'holiday' => '', 'business_hour' => '月〜土 12:00 - 22:00 日 12:00 - 20:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'SHACK-A-LUCK', 'gender_id' => 1, 'prefecture_id' => 4, 'area_id' => 27, 'city' => '仙台市', 'address' => '青葉区中央2-10-3', 'building' => 'MTビル2F', 'instagram_url' => 'https://www.instagram.com/shackaluck', 'holiday' => '', 'business_hour' => '', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'Shoes&Clothes.P', 'gender_id' => 1, 'prefecture_id' => 4, 'area_id' => 27, 'city' => '仙台市', 'address' => '若林区荒町130', 'building' => '高新ビル1F', 'instagram_url' => 'https://www.instagram.com/shoes.and.clothes_p', 'holiday' => '火曜日', 'business_hour' => 'Weekday 14:00〜22:00 Sat・Sun・Holidays 12:00〜22:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'SQUAT', 'gender_id' => 1, 'prefecture_id' => 4, 'area_id' => 27, 'city' => '仙台市', 'address' => '青葉区本町2-13-10', 'building' => '', 'instagram_url' => 'https://www.instagram.com/squat_used_clothing', 'holiday' => '', 'business_hour' => '11:00~20:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'Utah', 'gender_id' => 1, 'prefecture_id' => 4, 'area_id' => 27, 'city' => '仙台市', 'address' => '青葉区本町2-9-16', 'building' => '', 'instagram_url' => 'https://www.instagram.com/utahclothing', 'holiday' => '', 'business_hour' => '', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'shushubell', 'gender_id' => 1, 'prefecture_id' => 4, 'area_id' => 27, 'city' => '仙台市', 'address' => '青葉区国分町1-3-13', 'building' => '', 'instagram_url' => 'https://www.instagram.com/shushubell', 'holiday' => '不定休', 'business_hour' => '12:00-20:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'Real Monkey Sendai', 'gender_id' => 1, 'prefecture_id' => 4, 'area_id' => 27, 'city' => '仙台市', 'address' => '青葉区本町2-14-20', 'building' => '大貴本町ビル502', 'instagram_url' => 'https://www.instagram.com/real_monkey_sendai', 'holiday' => '', 'business_hour' => '', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'Room-9', 'gender_id' => 1, 'prefecture_id' => 4, 'area_id' => 27, 'city' => '仙台市', 'address' => '青葉区大町1-3-25', 'building' => '4F', 'instagram_url' => 'https://www.instagram.com/room____9', 'holiday' => '', 'business_hour' => '月〜金 12:00~17:00 土日祝 12:00~18:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'BEAGLE USED & VINTAGE', 'gender_id' => 1, 'prefecture_id' => 4, 'area_id' => 27, 'city' => '仙台市', 'address' => '青葉区立町21-1', 'building' => '', 'instagram_url' => 'https://www.instagram.com/beagle_sendai', 'holiday' => '', 'business_hour' => '12:00-20:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'elie', 'gender_id' => 2, 'prefecture_id' => 4, 'area_id' => 27, 'city' => '仙台市', 'address' => '青葉区本町2-13-10', 'building' => '菊田屋ビル3F', 'instagram_url' => 'https://www.instagram.com/elie.sendai', 'holiday' => '', 'business_hour' => '12:00-19:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'i my', 'gender_id' => 2, 'prefecture_id' => 4, 'area_id' => 27, 'city' => '仙台市', 'address' => '青葉区一番町3-10-3', 'building' => '川村ビル3F', 'instagram_url' => 'https://www.instagram.com/i_my_vintage', 'holiday' => '', 'business_hour' => '平日 12:00-18:00 土日 12:00-19:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'HOWDY', 'gender_id' => 1, 'prefecture_id' => 4, 'area_id' => 27, 'city' => '仙台市', 'address' => '青葉区一番町1-12-3', 'building' => '', 'instagram_url' => 'https://www.instagram.com/howdy_88', 'holiday' => '', 'business_hour' => '平日12:00-20:00 土日祝11:00-19:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'TRUE VINTAGE', 'gender_id' => 1, 'prefecture_id' => 4, 'area_id' => 27, 'city' => '仙台市', 'address' => '青葉区一番町1-6-20', 'building' => 'ライトハウスビル 102', 'instagram_url' => 'https://www.instagram.com/truevintage_sendai', 'holiday' => '', 'business_hour' => '', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
        ]);
    }
}
