<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ShopsTohokuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('shops')->insert([
            ['name' => 'SEESAW', 'gender_id' => 1, 'prefecture_id' => 2, 'area_id' => 28, 'city' => '弘前市', 'address' => '北瓦ケ町3-1', 'building' => 'キョウドウ第一ビル 一階A ', 'instagram_url' => 'https://www.instagram.com/seesaw_hirosaki', 'holiday' => '火曜日', 'business_hour' => '13:00-21:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'THE FICTION', 'gender_id' => 1, 'prefecture_id' => 2, 'area_id' => 28, 'city' => '弘前市', 'address' => '代官町56', 'building' => '', 'instagram_url' => 'https://www.instagram.com/the_fiction___', 'holiday' => '火曜日', 'business_hour' => 'Weekday 13:00-21:00 Sat&Sun 12:00-21:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'BUTTON UP CLOTHING', 'gender_id' => 1, 'prefecture_id' => 2, 'area_id' => 28, 'city' => '弘前市', 'address' => '大町3-10-8', 'building' => '', 'instagram_url' => 'https://www.instagram.com/buttonupclothing', 'holiday' => '', 'business_hour' => '', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'CRAZY GARDENS', 'gender_id' => 1, 'prefecture_id' => 2, 'area_id' => 28, 'city' => '弘前市', 'address' => '取上2-14-1', 'building' => '', 'instagram_url' => 'https://www.instagram.com/crazygardens', 'holiday' => '水曜日', 'business_hour' => '月-金 13:00-20:00 土日祝 12:00-20:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'CORRINA CORRINA', 'gender_id' => 1, 'prefecture_id' => 2, 'area_id' => 28, 'city' => '弘前市', 'address' => '土手町133-2', 'building' => '', 'instagram_url' => 'https://www.instagram.com/corrina2.vintage', 'holiday' => '木曜日', 'business_hour' => '12:00-18:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'Demonstrandum', 'gender_id' => 1, 'prefecture_id' => 2, 'area_id' => 29, 'city' => '八戸市', 'address' => '下長3-9-7', 'building' => '', 'instagram_url' => 'https://www.instagram.com/demonstrandum.dsd', 'holiday' => '火・水・木曜日(たまに休み返上あり)', 'business_hour' => '12:00-20:00 (土、日曜日、祝日12:00-19:00)', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'BELL EPOC', 'gender_id' => 1, 'prefecture_id' => 2, 'area_id' => 29, 'city' => '八戸市', 'address' => '下長2-2-24', 'building' => '', 'instagram_url' => 'https://www.instagram.com/bellepoc', 'holiday' => '', 'business_hour' => '', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'YellowBullbon', 'gender_id' => 1, 'prefecture_id' => 2, 'area_id' => 29, 'city' => '八戸市', 'address' => '糠塚字狐森18-51', 'building' => '', 'instagram_url' => 'https://www.instagram.com/yellowbullbon', 'holiday' => '', 'business_hour' => '不定期オープン 13:00〜19:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'rifs overall', 'gender_id' => 1, 'prefecture_id' => 2, 'area_id' => 29, 'city' => '八戸市', 'address' => '小中野8-15-21', 'building' => '', 'instagram_url' => 'https://www.instagram.com/rifs_overall', 'holiday' => '', 'business_hour' => '12:00-20:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'FANCYWALK', 'gender_id' => 1, 'prefecture_id' => 5, 'area_id' => 30, 'city' => '秋田市', 'address' => '中通5-5-31 ', 'building' => '', 'instagram_url' => 'https://www.instagram.com/fancywalkvintage', 'holiday' => '', 'business_hour' => '13:00-19:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'Alright', 'gender_id' => 1, 'prefecture_id' => 5, 'area_id' => 30, 'city' => '秋田市', 'address' => '中通2-8-1', 'building' => 'フォンテAKITA 2階', 'instagram_url' => 'https://www.instagram.com/alright_worldwide_recycle', 'holiday' => '', 'business_hour' => '', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'アンディ&キャロライン', 'gender_id' => 1, 'prefecture_id' => 5, 'area_id' => 30, 'city' => '秋田市', 'address' => '中通6-14-11', 'building' => '', 'instagram_url' => 'https://www.instagram.com/andy00caroline', 'holiday' => '', 'business_hour' => '主に晴れた土日 11:00〜17:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'gallant-doo', 'gender_id' => 1, 'prefecture_id' => 5, 'area_id' => 30, 'city' => '秋田市', 'address' => '広面字昼寝46-4', 'building' => '', 'instagram_url' => 'https://www.instagram.com/gallantdoo_akita2', 'holiday' => '', 'business_hour' => '平日13:00-19:00 土日祝10:00-19:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'TAO', 'gender_id' => 1, 'prefecture_id' => 3, 'area_id' => 31, 'city' => '盛岡市', 'address' => '上田3-1-53', 'building' => '', 'instagram_url' => 'https://www.instagram.com/taousedclothing', 'holiday' => '木曜日', 'business_hour' => '12:00-19:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'レトロブティックことり', 'gender_id' => 1, 'prefecture_id' => 3, 'area_id' => 31, 'city' => '盛岡市', 'address' => '夕顔瀬町20-52', 'building' => '', 'instagram_url' => 'https://www.instagram.com/cobicobi1129', 'holiday' => '火曜日', 'business_hour' => '12:00-19:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'LOVELOCK', 'gender_id' => 2, 'prefecture_id' => 3, 'area_id' => 31, 'city' => '盛岡市', 'address' => '開運橋通1-40', 'building' => '', 'instagram_url' => 'https://www.instagram.com/lovelock_morioka', 'holiday' => '', 'business_hour' => '11:00-19:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'Brownstone', 'gender_id' => 1, 'prefecture_id' => 3, 'area_id' => 31, 'city' => '盛岡市', 'address' => '開運橋通1-2', 'building' => '', 'instagram_url' => 'https://www.instagram.com/morioka_brownstone', 'holiday' => '', 'business_hour' => '11:00-19:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'one and only', 'gender_id' => 1, 'prefecture_id' => 3, 'area_id' => 31, 'city' => '盛岡市', 'address' => '本宮３-10-11', 'building' => '', 'instagram_url' => 'https://www.instagram.com/one_and_only_2007', 'holiday' => '', 'business_hour' => '', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'cheapchic', 'gender_id' => 1, 'prefecture_id' => 3, 'area_id' => 31, 'city' => '盛岡市', 'address' => '中央通1-12-1', 'building' => '', 'instagram_url' => 'https://www.instagram.com/cheapchic_5', 'holiday' => '不定休', 'business_hour' => '11:00-19:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'Sunny Collection', 'gender_id' => 1, 'prefecture_id' => 6, 'area_id' => 32, 'city' => '山形市', 'address' => '西田2-4-13', 'building' => '', 'instagram_url' => 'https://www.instagram.com/sunnycollection', 'holiday' => '', 'business_hour' => '', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'SQUAT', 'gender_id' => 1, 'prefecture_id' => 6, 'area_id' => 32, 'city' => '山形市', 'address' => '十日町4-3-14', 'building' => '', 'instagram_url' => 'https://www.instagram.com/squat_used_clothing', 'holiday' => '', 'business_hour' => '11:00-20:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => '古着倉庫 米沢店', 'gender_id' => 1, 'prefecture_id' => 6, 'area_id' => 33, 'city' => '米沢市', 'address' => '中田町514-1', 'building' => '', 'instagram_url' => 'https://www.instagram.com/furugisouko2017', 'holiday' => '', 'business_hour' => '平日 12:00-19:00 土日祝 11:00-19:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'jamming', 'gender_id' => 1, 'prefecture_id' => 6, 'area_id' => 32, 'city' => '山形市', 'address' => '本町1-7-20', 'building' => '', 'instagram_url' => 'https://www.instagram.com/jammingyamagata', 'holiday' => '', 'business_hour' => '11:00-18:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'ハングアウト', 'gender_id' => 1, 'prefecture_id' => 6, 'area_id' => 33, 'city' => '米沢市', 'address' => '中央3-10-23', 'building' => '', 'instagram_url' => 'https://www.instagram.com/hangout_yonezawa', 'holiday' => '', 'business_hour' => '', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'DESERT SNOW 郡山', 'gender_id' => 1, 'prefecture_id' => 7, 'area_id' => 34, 'city' => '郡山市', 'address' => '中町11-4', 'building' => 'ツタヤビル2階', 'instagram_url' => 'https://www.instagram.com/desert_koriyama', 'holiday' => '', 'business_hour' => '', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'CLOVER OVER DOVER', 'gender_id' => 3, 'prefecture_id' => 7, 'area_id' => 34, 'city' => '郡山市', 'address' => '中町7-8', 'building' => '文化マート', 'instagram_url' => 'https://www.instagram.com/clover_over_dover_0309', 'holiday' => '木曜日', 'business_hour' => '12:00-19:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 's.l.u.t koriyama vintage 本店', 'gender_id' => 1, 'prefecture_id' => 7, 'area_id' => 34, 'city' => '郡山市', 'address' => '清水台1-6-19', 'building' => '八幡第一ビル 1F', 'instagram_url' => 'https://www.instagram.com/s.l.u.t_koriyama_vintage', 'holiday' => '', 'business_hour' => '11:00-20:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 's.l.u.t koriyama vintage 2号店', 'gender_id' => 1, 'prefecture_id' => 7, 'area_id' => 34, 'city' => '郡山市', 'address' => '清水台2-13-24', 'building' => '今川ビル1F', 'instagram_url' => 'https://www.instagram.com/s.l.u.t_koriyama_vintage', 'holiday' => '', 'business_hour' => '11:00-20:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'A n d 1 9 3 1', 'gender_id' => 2, 'prefecture_id' => 7, 'area_id' => 34, 'city' => '郡山市', 'address' => '清水台1-6-9', 'building' => '八幡プラザビル一号館 1F', 'instagram_url' => 'https://www.instagram.com/and_1931', 'holiday' => '店休日18.19日', 'business_hour' => '12:00-18:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'ALL MY LOVING', 'gender_id' => 1, 'prefecture_id' => 7, 'area_id' => 34, 'city' => '郡山市', 'address' => '中町11-5', 'building' => 'スクエア郡山ビル1F', 'instagram_url' => 'https://www.instagram.com/allmyloving0520', 'holiday' => '第3火曜日', 'business_hour' => '10:00-19:30', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'A-USED CLOTHING HOUSE', 'gender_id' => 1, 'prefecture_id' => 7, 'area_id' => 34, 'city' => '郡山市', 'address' => '駅前1-4-6', 'building' => '', 'instagram_url' => 'https://www.instagram.com/a_used.clothing.house', 'holiday' => '', 'business_hour' => '11:30-19:30', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'Pickle', 'gender_id' => 1, 'prefecture_id' => 7, 'area_id' => 34, 'city' => '郡山市', 'address' => '神明町1-21', 'building' => '', 'instagram_url' => 'https://www.instagram.com/pickle_used', 'holiday' => '水曜日', 'business_hour' => '12:00-19:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'SPANKY&LORO', 'gender_id' => 1, 'prefecture_id' => 7, 'area_id' => 35, 'city' => '福島市', 'address' => '置賜町8-35', 'building' => '', 'instagram_url' => 'https://www.instagram.com/spankyloro', 'holiday' => '火曜日', 'business_hour' => '平日12:00-19:00 土日祝11:00-19:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'DAISYBELL', 'gender_id' => 2, 'prefecture_id' => 7, 'area_id' => 35, 'city' => '福島市', 'address' => '大町1-10', 'building' => '2F', 'instagram_url' => 'https://www.instagram.com/daisybell2015', 'holiday' => '火曜、木曜', 'business_hour' => '平日 12:00-17:00 土日 11:00-19:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'Olga used & vintage', 'gender_id' => 2, 'prefecture_id' => 7, 'area_id' => 34, 'city' => '郡山市', 'address' => '愛宕町1-27', 'building' => '3F', 'instagram_url' => 'https://www.instagram.com/olga____picasso', 'holiday' => '木曜日', 'business_hour' => '12:00-19:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'TRUNK23', 'gender_id' => 1, 'prefecture_id' => 7, 'area_id' => 35, 'city' => '福島市', 'address' => '永井川字沢田10-9', 'building' => '', 'instagram_url' => 'https://www.instagram.com/trunk23aj23', 'holiday' => '', 'business_hour' => '12:00-18:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'MellowOut', 'gender_id' => 1, 'prefecture_id' => 7, 'area_id' => 35, 'city' => '福島市', 'address' => '新町3-15', 'building' => '新町清水ビル2階', 'instagram_url' => 'https://www.instagram.com/mellowoutfukushima', 'holiday' => '水曜日', 'business_hour' => '11:00-19:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => "yellow's", 'gender_id' => 1, 'prefecture_id' => 7, 'area_id' => 36, 'city' => 'いわき市', 'address' => '平谷川瀬3-23-8', 'building' => '', 'instagram_url' => 'https://www.instagram.com/yellowsiwaki', 'holiday' => '', 'business_hour' => '', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'general store tabito', 'gender_id' => 1, 'prefecture_id' => 7, 'area_id' => 36, 'city' => 'いわき市', 'address' => '田人町黒田字河内33', 'building' => '', 'instagram_url' => 'https://www.instagram.com/gstabito66', 'holiday' => '不定休', 'business_hour' => '10:00-15:30', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'no.vel', 'gender_id' => 1, 'prefecture_id' => 7, 'area_id' => 36, 'city' => 'いわき市', 'address' => '平谷川瀬3-6-1', 'building' => '久善ビル12号', 'instagram_url' => 'https://www.instagram.com/no.veliwaki', 'holiday' => '不定休', 'business_hour' => '13:00-21:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'STEEZY USED CLOTHING', 'gender_id' => 1, 'prefecture_id' => 7, 'area_id' => 36, 'city' => 'いわき市', 'address' => '平字三倉66-4', 'building' => '', 'instagram_url' => 'https://www.instagram.com/steezy2014polo', 'holiday' => '', 'business_hour' => '', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
        ]);
    }
}
