<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ShopsGakugeidaiHatagayaMachidaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('shops')->insert([
            ['name' => 'MOOD', 'gender_id' => 1, 'prefecture_id' => 13, 'area_id' => 5, 'city' => '目黒区', 'address' => '鷹番3-7-13', 'building' => '深山ハウス1F', 'instagram_url' => 'https://www.instagram.com/moodnafurugi', 'holiday' => '金曜日', 'business_hour' => '14:00-21:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'TRAMPOT', 'gender_id' => 1, 'prefecture_id' => 13, 'area_id' => 5, 'city' => '目黒区', 'address' => '鷹番3-18-18', 'building' => '', 'instagram_url' => 'https://www.instagram.com/trampot2005', 'holiday' => '', 'business_hour' => '15:00-22:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'neiRo', 'gender_id' => 1, 'prefecture_id' => 13, 'area_id' => 5, 'city' => '目黒区', 'address' => '中央町1-15-21', 'building' => '102', 'instagram_url' => 'https://www.instagram.com/neiro_gakudai', 'holiday' => '木曜日', 'business_hour' => '12:00-21:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'endress', 'gender_id' => 1, 'prefecture_id' => 13, 'area_id' => 5, 'city' => '目黒区', 'address' => '鷹番2-20-13', 'building' => '1F', 'instagram_url' => 'https://www.instagram.com/endresstheshop', 'holiday' => '', 'business_hour' => '15:00-24:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => '7th', 'gender_id' => 1, 'prefecture_id' => 13, 'area_id' => 5, 'city' => '目黒区', 'address' => '鷹番2-20-2', 'building' => '三和ビル 1F', 'instagram_url' => 'https://www.instagram.com/7th_gakudai', 'holiday' => '', 'business_hour' => '', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'altnoi', 'gender_id' => 1, 'prefecture_id' => 13, 'area_id' => 5, 'city' => '目黒区', 'address' => '鷹番2-9-5', 'building' => '', 'instagram_url' => 'https://www.instagram.com/altnoi.gakugeidai', 'holiday' => '', 'business_hour' => '月-金 13:00-22:00 土日祝 13:00-21:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'FINN', 'gender_id' => 1, 'prefecture_id' => 13, 'area_id' => 5, 'city' => '目黒区', 'address' => '鷹番2-13-3', 'building' => '', 'instagram_url' => 'https://www.instagram.com/finn0424', 'holiday' => '木曜日', 'business_hour' => '13:00-20:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'Mistico Disco', 'gender_id' => 3, 'prefecture_id' => 13, 'area_id' => 5, 'city' => '目黒区', 'address' => '鷹番2-16-23', 'building' => '', 'instagram_url' => 'https://www.instagram.com/mistico_disco', 'holiday' => '月、木曜日', 'business_hour' => '14:30-20:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'Neuf', 'gender_id' => 3, 'prefecture_id' => 13, 'area_id' => 5, 'city' => '目黒区', 'address' => '鷹番3-5-5', 'building' => '102', 'instagram_url' => 'https://www.instagram.com/neuf.9', 'holiday' => '', 'business_hour' => '12:00-19:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'm', 'gender_id' => 1, 'prefecture_id' => 13, 'area_id' => 5, 'city' => '目黒区', 'address' => '鷹番2-8-21 ', 'building' => 'プラザ学芸大学WEST C', 'instagram_url' => 'https://www.instagram.com/m.usedclothingstore', 'holiday' => '', 'business_hour' => '月-金 14:00-23:00 土日祝 12:00-22:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'I ll', 'gender_id' => 1, 'prefecture_id' => 13, 'area_id' => 5, 'city' => '目黒区', 'address' => '鷹番2-17-11', 'building' => 'B1F', 'instagram_url' => 'https://www.instagram.com/ill_1215', 'holiday' => '水曜日', 'business_hour' => '15:00-23:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'EWER', 'gender_id' => 1, 'prefecture_id' => 13, 'area_id' => 5, 'city' => '目黒区', 'address' => '鷹番3-7-14', 'building' => '', 'instagram_url' => 'https://www.instagram.com/ewer____', 'holiday' => '', 'business_hour' => '13:00-20:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'paletown', 'gender_id' => 1, 'prefecture_id' => 13, 'area_id' => 20, 'city' => '渋谷区', 'address' => '西原2-21-10', 'building' => '', 'instagram_url' => 'https://www.instagram.com/paletown', 'holiday' => '', 'business_hour' => 'weekday 14:00-19:00 sat 13:00-19:00 sun,holi 13:00-18:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'NUTS&MILK', 'gender_id' => 1, 'prefecture_id' => 13, 'area_id' => 20, 'city' => '渋谷区', 'address' => '本町6-38-4', 'building' => '', 'instagram_url' => 'https://www.instagram.com/nuts_and_milk_hatagaya', 'holiday' => '水曜、ほぼ木曜', 'business_hour' => '12:00-19:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'annievintage', 'gender_id' => 2, 'prefecture_id' => 13, 'area_id' => 20, 'city' => '渋谷区', 'address' => '本町6-36-6', 'building' => '', 'instagram_url' => 'https://www.instagram.com/_annievintage_', 'holiday' => '', 'business_hour' => '14:00-19:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'SUMMER BONUS BUYS', 'gender_id' => 1, 'prefecture_id' => 13, 'area_id' => 20, 'city' => '渋谷区', 'address' => '幡ヶ谷2-19-4', 'building' => '', 'instagram_url' => 'https://www.instagram.com/summer_bonus_buys', 'holiday' => '月曜日', 'business_hour' => 'Weekday 14:00-20:00 Sat 13:00-19:00 Sun 13:00-18:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'suelto used vintage', 'gender_id' => 3, 'prefecture_id' => 13, 'area_id' => 20, 'city' => '渋谷区', 'address' => '笹塚3-18-9', 'building' => '四元ビル1F 1号室', 'instagram_url' => 'https://www.instagram.com/suelto_used_vintage', 'holiday' => '火曜日', 'business_hour' => '13:00-21:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'Time vintage', 'gender_id' => 2, 'prefecture_id' => 13, 'area_id' => 20, 'city' => '渋谷区', 'address' => '笹塚2-43-8', 'building' => '', 'instagram_url' => 'https://www.instagram.com/time_vintage_tokyo', 'holiday' => '', 'business_hour' => '平日13:00-21:00 土日祝12:00-20:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => '喜楽', 'gender_id' => 1, 'prefecture_id' => 13, 'area_id' => 20, 'city' => '杉並区', 'address' => '和泉1-8-15', 'building' => '', 'instagram_url' => 'https://www.instagram.com/kiraku_store', 'holiday' => '月曜日', 'business_hour' => '17:00-22:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'the charlie tokyo', 'gender_id' => 1, 'prefecture_id' => 13, 'area_id' => 20, 'city' => '杉並区', 'address' => '和泉1-3-16', 'building' => '', 'instagram_url' => 'https://www.instagram.com/thecharlietokyo', 'holiday' => '', 'business_hour' => '14:00-21:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'tempo', 'gender_id' => 1, 'prefecture_id' => 13, 'area_id' => 20, 'city' => '世田谷区', 'address' => '松原1-47-7', 'building' => '', 'instagram_url' => 'https://www.instagram.com/tempo.2016', 'holiday' => '', 'business_hour' => '', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'Shelly’s', 'gender_id' => 3, 'prefecture_id' => 13, 'area_id' => 20, 'city' => '世田谷区', 'address' => '赤堤4-36-22', 'building' => '', 'instagram_url' => 'https://www.instagram.com/shellys_yuki', 'holiday' => '月曜日', 'business_hour' => 'tue-fri 14:00-20:00 sat&sun 12:00-20:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'DANJIL', 'gender_id' => 3, 'prefecture_id' => 13, 'area_id' => 21, 'city' => '町田市', 'address' => '原町田6-24-17', 'building' => '町田ムセンビル101', 'instagram_url' => 'https://www.instagram.com/danjil2', 'holiday' => '', 'business_hour' => '12:00-20:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'Jolly Good Clothing', 'gender_id' => 1, 'prefecture_id' => 13, 'area_id' => 21, 'city' => '町田市', 'address' => '原町田2-2-1', 'building' => 'アムール町田 1F', 'instagram_url' => 'https://www.instagram.com/jollygoodclothing', 'holiday' => '月水木', 'business_hour' => '14:00-19:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'JAM', 'gender_id' => 3, 'prefecture_id' => 13, 'area_id' => 21, 'city' => '町田市', 'address' => '原町田4-9-16', 'building' => '第一 町田第一ビル 2F', 'instagram_url' => 'https://www.instagram.com/jamclothing_official', 'holiday' => '', 'business_hour' => '平日12:00-19:00 土日12:00-20:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'COSMIC JUMPER', 'gender_id' => 3, 'prefecture_id' => 13, 'area_id' => 21, 'city' => '町田市', 'address' => '中町1-18-3', 'building' => '', 'instagram_url' => 'https://www.instagram.com/cosmic.jumper', 'holiday' => '', 'business_hour' => '', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'MONKEY', 'gender_id' => 1, 'prefecture_id' => 13, 'area_id' => 21, 'city' => '町田市', 'address' => '中町1-18-16', 'building' => 'A-1ビル 1階', 'instagram_url' => 'https://www.instagram.com/monkey_machida', 'holiday' => '水曜日', 'business_hour' => '12:00-20:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'Aum vintage', 'gender_id' => 1, 'prefecture_id' => 13, 'area_id' => 6, 'city' => '世田谷区', 'address' => '池尻3-18-1', 'building' => '2F', 'instagram_url' => 'https://www.instagram.com/aumvtg', 'holiday' => '水曜日', 'business_hour' => '13:00-21:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'The Vintage Hook', 'gender_id' => 3, 'prefecture_id' => 13, 'area_id' => 4, 'city' => '目黒区', 'address' => '青葉台1-14-2', 'building' => '', 'instagram_url' => 'https://www.instagram.com/the.vintage.hook', 'holiday' => '', 'business_hour' => '13:00-20:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'Arca vintage', 'gender_id' => 1, 'prefecture_id' => 13, 'area_id' => 6, 'city' => '世田谷区', 'address' => '太子堂2-24-7', 'building' => '', 'instagram_url' => 'https://www.instagram.com/arca_vintage', 'holiday' => '', 'business_hour' => 'Mon-sat 14:00-21:00 Sun 13:00-20:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'anthem chill', 'gender_id' => 1, 'prefecture_id' => 13, 'area_id' => 18, 'city' => '目黒区', 'address' => '祐天寺2-8-17', 'building' => '2F', 'instagram_url' => 'https://www.instagram.com/anthem_chill', 'holiday' => '', 'business_hour' => '', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'hallelu', 'gender_id' => 1, 'prefecture_id' => 13, 'area_id' => 4, 'city' => '目黒区', 'address' => '上目黒1-19-1', 'building' => '高野ビル1F', 'instagram_url' => 'https://www.instagram.com/hallelu_tokyo', 'holiday' => '不定休', 'business_hour' => '14:00〜19:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'BARR', 'gender_id' => 1, 'prefecture_id' => 13, 'area_id' => 4, 'city' => '目黒区', 'address' => '上目黒2-12-13', 'building' => '前田ビル2F', 'instagram_url' => 'https://www.instagram.com/barr_tokyo', 'holiday' => '', 'business_hour' => '13:00-20:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => 'Spotman', 'gender_id' => 1, 'prefecture_id' => 13, 'area_id' => 17, 'city' => '杉並区', 'address' => '高円寺南2-22-7', 'building' => '', 'instagram_url' => 'https://www.instagram.com/spotman_koenji', 'holiday' => '', 'business_hour' => '12:00-19:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => '那由多', 'gender_id' => 2, 'prefecture_id' => 13, 'area_id' => 17, 'city' => '杉並区', 'address' => '高円寺南3-56-1', 'building' => '108', 'instagram_url' => 'https://www.instagram.com/nayuta_tokyo', 'holiday' => '', 'business_hour' => '13:00-20:00', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => '即興', 'gender_id' => 2, 'prefecture_id' => 13, 'area_id' => 17, 'city' => '杉並区', 'address' => '高円寺南3-59-14', 'building' => '', 'instagram_url' => 'https://www.instagram.com/sokkyou', 'holiday' => '', 'business_hour' => '13:00-19:30', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
            ['name' => '郊外SUBURBIA', 'gender_id' => 2, 'prefecture_id' => 13, 'area_id' => 17, 'city' => '杉並区', 'address' => '高円寺南3-56-5', 'building' => '102', 'instagram_url' => 'https://www.instagram.com/kougai.suburbia', 'holiday' => '', 'business_hour' => '', 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t'), 'created_user_id' => 1, 'updated_user_id' => 1],
        ]);
    }
}
